export const toureTypeData = [
  { id: 1, name: "Historical Tours", icon: "🏰", value: "Historical-Tours" },
  {
    id: 2,
    name: "Adventure Expeditions",
    icon: "🌄",
    value: "Adventure-Expeditions",
  },
  {
    id: 3,
    name: "Cultural Immersion",
    icon: "🌍",
    value: "Cultural-Immersion",
  },
  { id: 4, name: "Wildlife Safaris", icon: "🦓", value: "Wildlife-Safaris" },
  { id: 5, name: "Beach Escapes", icon: "🏖️", value: "Beach-Escapes" },
  { id: 6, name: "City Explorer", icon: "🌆", value: "City-Explorer" },
  { id: 7, name: "Mountain Trekking", icon: "⛰️", value: "Mountain-Trekking" },
  { id: 8, name: "Culinary Tours", icon: "🍽️", value: "Culinary-Tours" },
  { id: 9, name: "Luxury Getaways", icon: "🌟", value: "Luxury-Getaways" },
  {
    id: 10,
    name: "Photography Expeditions",
    icon: "📷",
    value: "Photography-Expeditions",
  },
  { id: 11, name: "Wellness Retreats", icon: "🌿", value: "Wellness-Retreats" },
  { id: 12, name: "Island Hopping", icon: "🏝️", value: "Island-Hopping" },
  { id: 13, name: "Educational Tours", icon: "🎓", value: "Educational-Tours" },
];
